# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
target 'OSChina' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OSChina
  pod 'Alamofire', '~> 4.5.1'
  pod 'SVProgressHUD', '~> 2.2.2'
  pod 'SDWebImage', '~> 4.2.1'
  pod 'SnapKit', '~> 4.0.0'
  
end
